# Setup
timezone: America/New_York
# environment: staging

# Building
destination: ./GYM-000

exclude:
  - 'docker-compose.yml'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
  - '.jekyll-cache'
  - 'local'

# repository: gymnasium/gymcms

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

