name: "GYM-000 Release"
on:
  push:
    branches: [ main ]

jobs:
  generate-release:
    name: "Generate Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/jekyll-build-pages@v2
        with: 
          destination: "GYM-000"


        
