name: "GYM-000 Release"
on:
  push:
    branches: [ main ]

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Build courseware
        run: bundle exec jekyll build
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Commit the generated assets back into the repo
        


        
