name: "GYM-000 Release"
on:
  push:
    branches: [ main ]

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/jekyll-build-pages@v1
        name: "Jekyll the bits"
        with: 
          destination: "GYM-000"
      - name: "Kill that CSS file!"
        run: rm GYM-000/assets/css/style.css && rmdir GYM-000/assets/css
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: "Commit the generated bits back to the repo"


        
